apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dzyp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzyp
    app.kubernetes.io/part-of: byoc-app-aayy
  name: dzyp
spec:
  rules:
  - host: dzyp-byoc-cpek-tenant.apps.543980c7cf61d82c48b5.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: dzyp
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
