apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dzyp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzyp
    app.kubernetes.io/part-of: byoc-app-aayy
  name: dzyp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: dzyp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: dzyp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-cpek-tenant/byoc-app-aayy/dzyp@sha256:a851bda3f262b29003d376d6258679c4edca88c27bb4fe8eab4dbc09035be402
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
